spring:
    application:
        name: fitbit_tracker
    datasource:
        username: root
        password: rootroot
        url: jdbc:mysql://localhost:3306/fitbit_tracker_db
    jpa:
        hibernate:
            ddl-auto: update